### ISSUE TITLE
add option to disable formatting for thousands id IN (....)

### ISSUE THREAD

**Issue by morr** [pinzolo/rails-flog#16]
![monosnap 2017-01-20 11-33-11](https://cloud.githubusercontent.com/assets/134610/22141699/4b4920fc-df04-11e6-9822-dba086dcf093.png)

**Comment by pinzolo** [comment]
Sorry, `rails-flog` uses [sonota88/anbt\-sql\-formatter: A tool for SQL formatting written in Ruby\.](https://github.com/sonota88/anbt-sql-formatter) for formatting SQL.
It does not provide that feature.
So, now `rails-flog` does not provide that feature.

**Comment by pinzolo** [comment]
https://github.com/sonota88/anbt-sql-formatter/pull/10

**Comment by pinzolo** [comment]
v1.5.0 released now. Please use it.
